baseurl = "https://ivymarkwell.github.io"
languageCode = "en-us"
theme = "hello-friend-ng"
publishDir = "ivymarkwell.github.io"
pluralizeListTitles = false

[author]
  name = "Ivy Markwell"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  contentTypeName = "posts"
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:me@ivymarkwell.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ivymarkwell"

  [[params.social]]
    name = "medium"
    url  = "https://medium.com/@ivymarkwell"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/ivy-m-257540127/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/ivymarkwell"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/ivyymarkwell/"

[languages]
  [languages.en]
    title = "Ivy Markwell"

    [languages.en.params.logo]
      logoText = "cd ivymarkwell/"
      logoHomeLink = "/"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Photography"
        url = "/photography"

